version: 2
jobs:
    buildandrunright:
        docker:
            - image: sensirion/embedded-ci:2.1.0
        steps:
            - checkout
            - run: gcc -o arguments main.c
            - run: arguments hallo
    buildandrunwrong:
        docker:
            - image: sensirion/embedded-ci:2.1.0
        steps:
            - checkout
            - run: gcc -o arguments main.c
            - run: arguments hallo
workflows:
    version: 2 
    testtwice:
        jobs:
            - buildandrunright:
            - buildandrunwrong:
                requires:
                    - buildandrunright
                filters:
                    branches:
                        only: master

